# Generated by Django 5.1.2 on 2024-12-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
